---
- name: Set up WireGuard VPN
  hosts: all
  become: true

  roles:
    - geerlingguy.docker

  vars:
    username: ivan

  vars_prompt:
    - name: password
      prompt: "Введите пароль для пользователя {{username}}..."
      private: true
      encrypt: sha512_crypt
      confirm: true

  tasks:
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Ensure sudo is installed
      become: true
      ansible.builtin.apt:
        name: sudo
        state: present
    - name: Ensure login user is present
      become: true
      ansible.builtin.user:
        user: "{{ username }}"
        password: "{{ password }}"
        shell: /bin/bash
        state: present
        groups:
          - sudo
    - name: Ensure service directory exists
      become: true
      ansible.builtin.file:
        dest: /srv/wg-easy
        state: directory
        mode: "0755"
    - name: Ensure compose file is in the service directory
      become: true
      ansible.builtin.copy:
        src: compose.yml
        dest: /srv/wg-easy/compose.yml
        mode: "0644"
    - name: Deply wg-easy with docker-compose
      community.docker.docker_compose_v2:
        project_src: /srv/wg-easy
        files:
          - compose.yml
