---
- name: Set up WireGuard VPN
  hosts: all
  become: true

  roles:
    - geerlingguy.docker

  vars_prompt:
    - name: wg_password
      prompt: Enter password for wg-easy web ui...
      confirm: true
      encrypt: bcrypt

  tasks:
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Ensure sudo is installed
      become: true
      ansible.builtin.apt:
        name: sudo
        state: present
    - name: Ensure ufw is installed
      ansible.builtin.apt:
        name: ufw
        state: present
    - name: Ensure service directory exists
      become: true
      ansible.builtin.file:
        dest: /srv/wg-easy
        state: directory
        mode: "0755"
    - name: Ensure compose file is in the service directory
      become: true
      ansible.builtin.template:
        src: compose.yml.j2
        dest: /srv/wg-easy/compose.yml
        mode: "0644"
    - name: Deploy wg-easy with docker-compose
      community.docker.docker_compose_v2:
        project_src: /srv/wg-easy
        files:
          - compose.yml
    - name: Ensure ufw blocks incoming traffic by default
      community.general.ufw:
        default: deny
    - name: Ensure ufw limits SSH traffic
      community.general.ufw:
        rule: limit
        port: ssh
        proto: tcp
    - name: Ensure ufw allows traffic to WireGuard
      community.general.ufw:
        rule: allow
        port: "52820"
        proto: udp
    - name: Ensure ufw is enabled
      community.general.ufw:
        state: enabled
