---
- name: Set up WireGuard VPN
  hosts: all

  vars:
    username: ivan

  vars_prompt:
    - name: password
      prompt: "Введите пароль для пользователя {{username}}..."
      private: true
      encrypt: sha512_crypt
      confirm: true

  tasks:
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Ensure sudo is installed
      become: true
      ansible.builtin.apt:
        name: sudo
        state: present
    - name: Ensure login user is present
      become: true
      ansible.builtin.user:
        user: "{{ username }}"
        password: "{{ password }}"
        shell: /bin/bash
        state: present
        groups:
          - sudo
    - name: Ensure systemd lingering is enabled
      become: true
      ansible.builtin.command:
        cmd: loginctl enable-linger ivan
        creates: /var/lib/systemd/linger/ivan
    - name: Ensure user has access to lingering directory
      become: true
      ansible.builtin.file:
        path: /var/lib/systemd/linger/ivan
        group: ivan
        owner: ivan
    - name: Ensure podman is installed
      become: true
      ansible.builtin.apt:
        name: podman
        state: present
    - name: Ensure directory for quadlets exists for login user
      become: true
      ansible.builtin.file:
        dest: /home/ivan/.config/containers/systemd
        state: directory
        owner: ivan
        group: ivan
        mode: "0755"
    - name: Ensure wg-easy quadlet is present in login user home
      become: true
      ansible.builtin.copy:
        src: ./wg-easy.container
        dest: /home/ivan/.config/containers/systemd/WgEasy.container
        owner: ivan
        group: ivan
        mode: "0644"
